# WCAG Compliance Testing Template
# Optimized for accessibility auditing and ADA/Section 508 compliance
# Focus: WCAG 2.1 Level AA compliance, screen reader compatibility

# Target Configuration
target:
  url: "https://example.com"  # Replace with your website

  # Optional authentication
  auth:
    type: "basic"
    username: "{{ SECRET:compliance:username }}"
    password: "{{ SECRET:compliance:password }}"

  headers:
    User-Agent: "WebTestool/2.0 Accessibility Scanner"

# Crawler Configuration
crawler:
  max_pages: 1000
  max_depth: 10
  crawl_delay: 0.5

  # Comprehensive crawling for full site audit
  respect_robots_txt: true
  follow_redirects: true

  # Include all page types
  include_patterns:
    - "/*"

  exclude_patterns:
    - "/admin/*"
    - "/api/*"

# Modules Configuration
modules:
  # Accessibility - Primary Focus
  accessibility:
    enabled: true
    priority: critical

    # WCAG 2.1 Level AA compliance
    wcag_level: "AA"
    wcag_version: "2.1"

    tests:
      # Perceivable
      - text_alternatives:
          enabled: true
          # 1.1.1 Non-text Content
          check_image_alt: true
          check_decorative_images: true
          check_complex_images: true
          check_image_buttons: true
          check_audio_alternatives: true
          check_video_alternatives: true

      - time_based_media:
          enabled: true
          # 1.2.x Audio and Video
          check_captions: true
          check_audio_descriptions: true
          check_transcripts: true
          check_live_captions: true

      - adaptable:
          enabled: true
          # 1.3.x Info and Relationships
          check_semantic_structure: true
          check_headings_hierarchy: true
          check_lists_markup: true
          check_tables_structure: true
          check_form_labels: true
          check_meaningful_sequence: true
          check_sensory_characteristics: false

      - distinguishable:
          enabled: true
          # 1.4.x Color and Contrast
          check_color_contrast: true
          contrast_ratio_normal: 4.5  # WCAG AA
          contrast_ratio_large: 3.0   # WCAG AA
          check_color_usage: true
          check_audio_control: true
          check_text_resize: true
          check_images_of_text: true
          check_reflow: true
          check_non_text_contrast: true
          check_text_spacing: true
          check_content_on_hover: true

      # Operable
      - keyboard_accessible:
          enabled: true
          # 2.1.x Keyboard Access
          check_keyboard_access: true
          check_no_keyboard_trap: true
          check_keyboard_shortcuts: true
          check_character_key_shortcuts: true

      - enough_time:
          enabled: true
          # 2.2.x Timing
          check_timing_adjustable: true
          check_pause_stop_hide: true
          check_no_timing: false
          check_interruptions: true
          check_reauthentication: true
          check_timeouts: true

      - seizures:
          enabled: true
          # 2.3.x Seizures and Physical Reactions
          check_three_flashes: true
          check_animation: true

      - navigable:
          enabled: true
          # 2.4.x Navigation
          check_bypass_blocks: true
          check_page_titled: true
          check_focus_order: true
          check_link_purpose: true
          check_multiple_ways: true
          check_headings_labels: true
          check_focus_visible: true

      - input_modalities:
          enabled: true
          # 2.5.x Input Modalities
          check_pointer_gestures: true
          check_pointer_cancellation: true
          check_label_in_name: true
          check_motion_actuation: true
          check_target_size: true

      # Understandable
      - readable:
          enabled: true
          # 3.1.x Readable
          check_language: true
          check_language_of_parts: true
          check_unusual_words: false
          check_abbreviations: false
          check_reading_level: false
          check_pronunciation: false

      - predictable:
          enabled: true
          # 3.2.x Predictable
          check_on_focus: true
          check_on_input: true
          check_consistent_navigation: true
          check_consistent_identification: true
          check_change_on_request: true

      - input_assistance:
          enabled: true
          # 3.3.x Input Assistance
          check_error_identification: true
          check_labels_instructions: true
          check_error_suggestion: true
          check_error_prevention: true
          check_help: true
          check_error_prevention_all: true

      # Robust
      - compatible:
          enabled: true
          # 4.1.x Compatible
          check_parsing: true
          check_name_role_value: true
          check_status_messages: true

    # Screen Reader Testing
    screen_reader:
      enabled: true
      test_with_nvda: true
      test_with_jaws: false
      check_aria_labels: true
      check_aria_roles: true
      check_aria_states: true
      check_live_regions: true

    # Keyboard Navigation
    keyboard_testing:
      enabled: true
      test_tab_order: true
      test_skip_links: true
      test_focus_indicators: true
      test_modal_traps: false  # Should trap focus in modals

    # Color Contrast
    contrast_testing:
      enabled: true
      tools:
        - "axe-core"
        - "contrast-checker"
      check_all_elements: true
      ignore_hidden: true

  # SEO (Related to accessibility)
  seo:
    enabled: true
    priority: medium

    tests:
      - semantic_html:
          enabled: true
          check_headings: true
          check_landmarks: true

      - meta_tags:
          enabled: true
          check_title: true
          check_description: true
          check_lang_attribute: true

  # Security (Basic checks)
  security:
    enabled: true
    priority: low

    tests:
      - headers:
          enabled: true
          required_headers:
            - "Content-Security-Policy"
            - "X-Content-Type-Options"

      - ssl:
          enabled: true
          check_certificate: true
          minimum_tls_version: "1.2"

  # Performance (Page load affects accessibility)
  performance:
    enabled: true
    priority: low

    tests:
      - page_speed:
          enabled: true
          threshold_ms: 3000

# Automated Testing Tools Integration
tools:
  # Axe-core (Deque)
  axe_core:
    enabled: true
    run_only_tags:
      - "wcag2a"
      - "wcag2aa"
      - "wcag21a"
      - "wcag21aa"

  # Pa11y
  pa11y:
    enabled: true
    standard: "WCAG2AA"
    runners:
      - "axe"
      - "htmlcs"

  # WAVE (WebAIM)
  wave:
    enabled: false  # Requires API key
    api_key: "{{ SECRET:wave:api_key }}"

# Reporting
reporting:
  format: "html"
  output_dir: "reports/compliance"

  sections:
    - "executive_summary"
    - "wcag_compliance_summary"
    - "violations_by_level"
    - "violations_by_principle"
    - "manual_checks_required"
    - "recommendations"
    - "remediation_guide"

  # Compliance-specific options
  include_wcag_references: true
  include_code_examples: true
  include_before_after: true

  # Severity mapping
  map_to_wcag_level: true

  # Export formats
  exports:
    - "html"
    - "pdf"
    - "json"
    - "csv"
    - "wcag-em"  # WCAG-EM Report Tool format

  # Screenshots
  capture_screenshots: true
  screenshot_violations: true

# Manual Testing Checklist
manual_checks:
  enabled: true

  # Items that require human review
  checklist:
    - "Keyboard navigation flow"
    - "Screen reader announcements"
    - "Focus indicators visibility"
    - "Color contrast in all states"
    - "Video captions accuracy"
    - "Audio descriptions quality"
    - "Form error messages clarity"
    - "Skip link functionality"
    - "Responsive design accessibility"
    - "Touch target sizes"

# Compliance Standards
compliance:
  standards:
    - "WCAG 2.1 Level AA"
    - "ADA"
    - "Section 508"
    - "EN 301 549"

  # Audit type
  audit_type: "full"  # "full", "partial", "spot-check"

  # Conformance level
  target_level: "AA"

# Browser Testing
browsers:
  - name: "chrome"
    versions: ["latest"]
  - name: "firefox"
    versions: ["latest"]
  - name: "safari"
    versions: ["latest"]
  - name: "edge"
    versions: ["latest"]

# Device Testing
devices:
  - type: "desktop"
    viewport: "1920x1080"
  - type: "tablet"
    viewport: "768x1024"
  - type: "mobile"
    viewport: "375x667"

# Notifications
notifications:
  enabled: true

  on_complete:
    email: "accessibility-team@example.com"
    include_summary: true

# Cache
cache:
  enabled: true
  ttl: 3600

# Rate Limiting
rate_limit:
  requests_per_second: 5
  max_concurrent: 2

# Logging
logging:
  level: "INFO"
  file: "logs/compliance_scan.log"
  rotate: true
